#list of Telegram channel  
telegram_channels:
  
  - name: "Zemen ExpressÂ®"
    username: "ZemenExpress"
    category: "general_ecommerce"
    priority: 1
  - name: "NEVA COMPUTERÂ®"
    username: "nevacomputer"
    category: "Electronics"
    priority: 1
  - name: "áˆ˜áŠáˆ»á‹¬"
    username: "meneshayeofficial"
    category: "local_business"
    priority: 2
  - name: "EthioBrandÂ®"
    username: "ethio_brand_collection"
    category: "Shoe_and_cloth"
    priority: 2
  - name: "áˆá‹© áŠ¥á‰ƒ"
    username: "Leyueqa"
    category: "gadgets"
    priority: 3

  - name: "Shewa Brand"
    username: "Shewabrand"
    category: "general_ecommerce"
    priority: 1
  - name: "HellooMarket"
    username: "helloomarketethiopia"
    category: "general_ecommerce"
    priority: 1
  - name: "áˆá‹°áˆ­áŠ• áˆ¾á’áŠ•áŒ áˆ´áŠ•á‰°áˆ­ MODERN SHOPPING "
    username: "modernshoppingcenter"
    category: "general_ecommerce"
    priority: 2
  - name: "qnash.com - á‰…áŠ“áˆ½ Â®ï¸"
    username: "qnashcom"
    category: "general_ecommerce"
    priority: 2
  - name: "Fashion tera"
    username: "Fashiontera"
    category: "Shoe_and_cloth"
    priority: 3

  - name: "áŠ©áˆ©/kuru/ ğŸ‡ªğŸ‡¹ wear Â®ï¸"
    username: "kuruwear"
    category: "gadgets"
    priority: 3
  - name: "áŠ á‹³áˆ› áŒˆá‰ á‹« - Adama gebeya"
    username: "gebeyaadama"
    category: "general_ecommerce"
    priority: 3

  - name: "4Free MarketğŸ‡ªğŸ‡¹"
    username: "forfreemarket"
    category: "general_ecommerce"
    priority: 3
  - name: "CLASSY BRAND Â®"
    username: "classybrands"
    category: "Shoe_and_cloth"
    priority: 3
  - name: "áˆ›áˆ«áŠª áƒªĞ¯ï¾‘Å‹ã®â„¢"
    username: "marakibrand"
    category: "Shoe_and_cloth"
    priority: 3
  - name: "â’¶â“‡â’¶â’¹â’¶ â’·â“‡â’¶â“ƒâ’¹"
    username: "aradabrand2"
    category: "Shoe_and_cloth"
    priority: 3
  - name: "ğŸ‡ªğŸ‡¹ ğŸ“¡ MARAKI BRANDSğŸŒğŸ†"
    username: "@marakisat2"
    category: "Electronics"
    priority: 3
  - name: "BELLA CLASSICÂ®"
    username: "belaclassic"
    category: "Shoe_and_cloth"
    priority: 3
  - name: "AwasMart-áŠ á‹‹áˆµáˆ›áˆ­á‰µğŸ"
    username: "AwasMart"
    category: "general_ecommerce"
    priority: 3
  - name: "qnash.com - á‰…áŠ“áˆ½ Â®ï¸"
    username: "qnashcom"
    category: "general_ecommerce"
    priority: 3

scraping_config:
  max_messages_per_channel: 1000
  date_range_days: 60
  include_media: true
  retry_attempts: 3
  delay_between_requests: 2

 